<?php
/**
 * Copyright © 2015 ShopGo. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \ShopGo\AmazonSns\Block\Adminhtml\System\Config\Subscribe
 */
?>
<script>
require([
    'Magento_Ui/js/modal/alert',
    'prototype'
], function(alert) {

//<![CDATA[
    function subscribe() {
        var message = $('subscribe_result');

        new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxUrl() ?>', {
            onSuccess: function(response) {
                var result = '<?php /* @escapeNotVerified */ echo __('Error during subscription to SNS topic.') ?>';

                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result   = response.message;
                    }

                    alert({
                        content: response.message
                    });
                } catch (e) {
                    alert({
                        content: result
                    });
                }
            }
        });
    }

    window.subscribe = subscribe;
//]]>

});
</script>
<div class="actions actions-subscribe">
    <div id="subscribe_result" class="message-subscribe hidden"></div>
    <button onclick="javascript:subscribe(); return false;" class="action-subscribe" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
